services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"
    volumes:
      - namenode-data:/hadoop/dfs/name

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
    depends_on:
      - namenode
    volumes:
      - datanode-data:/hadoop/dfs/data

  resourcemanager:
    image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.2.1-java8
    container_name: resourcemanager
    depends_on:
      - namenode
    ports:
      - "8088:8088"

  nodemanager:
    image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.2.1-java8
    container_name: nodemanager
    depends_on:
      - resourcemanager

  spark-master:
    image: apache/spark:3.5.0
    container_name: spark-master
    environment:
      - SPARK_MODE=master
    command: >
      bash -c "/opt/spark/sbin/start-master.sh && tail -f /dev/null"
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - namenode

  spark-worker:
    image: apache/spark:3.5.0
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
    command: >
      bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
    depends_on:
      - spark-master

  nifi:
    image: apache/nifi:1.28.1
    container_name: nifi
    ports:
      - "8081:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_BOOTSTRAP_CONF_DIR=/opt/nifi/nifi-current/conf
    volumes:
      - nifi-conf:/opt/nifi/nifi-current/conf
      - nifi-logs:/opt/nifi/nifi-current/logs
      #- ./nifi/conf:/opt/nifi/nifi-current/conf
      #- ./nifi/logs:/opt/nifi/nifi-current/logs
      - ./work/dataset:/dataset
      - ./nifi/conf/hadoop:/opt/nifi/nifi-current/conf/hadoop

  jupyter:
    image: jupyter/pyspark-notebook:x86_64-spark-3.5.0
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - PYSPARK_SUBMIT_ARGS=--master spark://spark-master:7077 pyspark-shell
    depends_on:
      - spark-master

volumes:
  namenode-data:
  datanode-data:
  nifi-conf:
  nifi-logs: